# Site settings
title: CounterPAC
description: > # this means to ignore newlines until "baseurl:"
  As our elections become increasingly flooded with special interest money, Americans have 
  lost hope in our democracy. CounterPAC has a plan to restore it.
url: "http://counterpac.org" # production
paginate: 10
paginate_path: '/blog/page:num/'